// Generated by zinc (ZN-022): a function of the module per C++ function, over the interpreter's register window.
#include "rt/rt.h"
#include "zn/ops.h"

using namespace zn;
using namespace zn::rt;

static const unsigned char kModule[] = {
  90,66,67,50,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  2,0,0,0,4,0,0,0,109,97,105,110,0,0,1,0,5,0,0,0,3,0,32,0,
  121,0,1,0,145,0,0,0,151,0,0,0,123,0,0,0,0,0,0,0,0,0,0,0,
  3,0,0,0,102,105,98,1,1,1,4,0,23,0,0,0,120,0,0,2,3,0,0,0,
  122,0,0,0,99,1,0,255,120,1,0,2,7,0,0,0,100,12,0,0,99,2,1,255,
  121,2,1,0,99,3,1,254,121,3,1,0,5,1,2,3,99,0,0,254,120,0,0,2,
  16,0,0,0,100,21,0,0,99,2,0,255,121,2,1,0,99,3,0,254,121,3,1,0,
  5,0,2,3,5,0,1,0,122,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};

static int f0(Machine& m, Slot* r);
static int f1(Machine& m, Slot* r);

// function 0
static int f0(Machine& m, Slot* r) {
  if (__builtin_expect(m.depth >= kMaxCallDepth, 0)) { m.error = "stack overflow"; return 2; }
  ++m.depth;
  r[0] = zn::ops::sx(32);
  { int st = f1(m, r + 0); if (__builtin_expect(st != 0, 0)) { if (st == 1) { Obj* e = m.thrown; } --m.depth; return st; } }
  *m.out += std::to_string(static_cast<std::int64_t>(r[0]));
  *m.out += '\n';
  { --m.depth; return 0; }
  --m.depth;
  return 0;
}

// function 1
static int f1(Machine& m, Slot* r) {
  if (__builtin_expect(m.depth >= kMaxCallDepth, 0)) { m.error = "stack overflow"; return 2; }
  ++m.depth;
  if (zn::ops::JGeIK(r[0], 2)) goto L3;
  { r[0] = r[0]; --m.depth; return 0; }
L3:
  r[1] = zn::ops::AddI32K(r[0], -1);
  if (zn::ops::JGeIK(r[1], 2)) goto L7;
  goto L12;
L7:
  r[2] = zn::ops::AddI32K(r[1], -1);
  { int st = f1(m, r + 2); if (__builtin_expect(st != 0, 0)) { if (st == 1) { Obj* e = m.thrown; } --m.depth; return st; } }
  r[3] = zn::ops::AddI32K(r[1], -2);
  { int st = f1(m, r + 3); if (__builtin_expect(st != 0, 0)) { if (st == 1) { Obj* e = m.thrown; } --m.depth; return st; } }
  r[1] = zn::ops::AddI32(r[2], r[3]);
L12:
  r[0] = zn::ops::AddI32K(r[0], -2);
  if (zn::ops::JGeIK(r[0], 2)) goto L16;
  goto L21;
L16:
  r[2] = zn::ops::AddI32K(r[0], -1);
  { int st = f1(m, r + 2); if (__builtin_expect(st != 0, 0)) { if (st == 1) { Obj* e = m.thrown; } --m.depth; return st; } }
  r[3] = zn::ops::AddI32K(r[0], -2);
  { int st = f1(m, r + 3); if (__builtin_expect(st != 0, 0)) { if (st == 1) { Obj* e = m.thrown; } --m.depth; return st; } }
  r[0] = zn::ops::AddI32(r[2], r[3]);
L21:
  r[0] = zn::ops::AddI32(r[1], r[0]);
  { r[0] = r[0]; --m.depth; return 0; }
  --m.depth;
  return 0;
}

static int (*const kNatives[])(Machine&, Slot*) = {f0, f1};

// The engine of a compiled program: run the native code of the function.
bool zn::rt::Machine::exec(const Func* f, Slot* base) {
  int st = f->native(*this, base);
  if (st == 1) { error = "panic: Uncaught " + exceptionText(thrown); thrown = nullptr; return false; }
  return st == 0;
}

int main() {
  return zn::rt::runProgram(kModule, sizeof kModule, kNatives, 2);
}
