// Generated by zinc (ZN-022): a function of the module per C++ function, over the interpreter's register window.
#include "rt/rt.h"
#include "zn/host.h"
#include "zn/ops.h"

using namespace zn;
using namespace zn::rt;

// The checks every function repeats, short (ZN-604): zt and ze are the messages of the function's error exits Ltrap and Lrterr.
#define ZTRAP(msg) { zt = (msg); goto Ltrap; }
#define ZNULLREF ZTRAP(op::kNullRef)
#define ZNULL(x) if (__builtin_expect(!(x), 0)) ZNULLREF
#define ZCHK(call) if (__builtin_expect((zt = (call)) != nullptr, 0)) goto Ltrap;
#define ZRTERR if (__builtin_expect(e != nullptr, 0)) { ze = e; goto Lrterr; }
#define ZST if (__builtin_expect(st != 0, 0)) return st;
#define ZRETAIN(x) op::retainC(x)
#define ZRELEASE(x) ZCHK(op::releaseC(m, x))
#define ZSTR(k) reinterpret_cast<Slot>(m.strConsts[k])
#define ZOBJ(cls, x) reinterpret_cast<Z_C##cls*>(x)
#define ZSETG(g, x) { Slot old = m.globals[g]; m.globals[g] = (x); if (m.globalRef[g]) op::dropC(m, old); }
#define ZVIRT(x, sel) const char* ce = nullptr; Slot vt = (x); const Func* cf = op::virtualTarget(&vt, 0, sel, ce); if (__builtin_expect(ce != nullptr, 0)) ZTRAP(ce)
// a window outside the stack (the temporary one of an exception text, a native callback) is not checked against its end
#define ZFN static
#define ZSTACK(n) if (__builtin_expect(op::stackLow(m) || (win + (n) > m.stackEnd && win >= m.stack && win < m.stackEnd), 0)) { m.error = "stack overflow"; return 2; }

ZFN int f0(Machine& m, Slot* r);
ZFN int f1(Machine& m, Slot* r);
ZFN Slot t1(Machine& m, Slot);

// function 0
ZFN int f0(Machine& m, Slot* win) {
  const char* zt; const char* ze;
  ZSTACK(1)
  Slot r[1];
  r[0] = zn::ops::sx(32);
  { win[0] = r[0]; int st = f1(m, win + 0); r[0] = win[0]; ZST }
  *m.out += std::to_string(static_cast<std::int64_t>(r[0]));
  *m.out += '\n';
  return 0;
  return 0;
}

// function 1 (typed)
ZFN Slot t1(Machine& m, Slot a0) {
  if (__builtin_expect(op::stackLow(m), 0)) { m.error = "stack overflow"; m.failed = true; return 0; }
  Slot r0 = a0;
  Slot r1;
  Slot r2;
  Slot r3;
  if (zn::ops::JGeIK(r0, 2)) goto L3;
  return r0;
L3:
  r1 = zn::ops::AddI32K(r0, -1);
  if (zn::ops::JGeIK(r1, 2)) goto L7;
  goto L12;
L7:
  r2 = zn::ops::AddI32K(r1, -1);
  { Slot v = t1(m, r2); if (__builtin_expect(m.failed, 0)) return 0; r2 = v; }
  r3 = zn::ops::AddI32K(r1, -2);
  { Slot v = t1(m, r3); if (__builtin_expect(m.failed, 0)) return 0; r3 = v; }
  r1 = zn::ops::AddI32(r2, r3);
L12:
  r0 = zn::ops::AddI32K(r0, -2);
  if (zn::ops::JGeIK(r0, 2)) goto L16;
  goto L21;
L16:
  r2 = zn::ops::AddI32K(r0, -1);
  { Slot v = t1(m, r2); if (__builtin_expect(m.failed, 0)) return 0; r2 = v; }
  r3 = zn::ops::AddI32K(r0, -2);
  { Slot v = t1(m, r3); if (__builtin_expect(m.failed, 0)) return 0; r3 = v; }
  r0 = zn::ops::AddI32(r2, r3);
L21:
  r0 = zn::ops::AddI32(r1, r0);
  return r0;
  return 0;
}

ZFN int f1(Machine& m, Slot* r) {
  m.failed = false;
  Slot v = t1(m, r[0]);
  if (__builtin_expect(m.failed, 0)) return 2;
  r[0] = v;
  return 0;
}

static const char kModule[] = 
  "\12ZBC2\7'\0*\2\0\0\0\4\0\0\0main\0\0\1\0\1\0\0\0\1\27\0\42\3\0\0\0fib\1\1\1\4\0\1\0\0\0\1/\0";
static const unsigned kModuleSize = 52;

static int (*const kNatives[])(Machine&, Slot*) = {f0, f1};

// The engine of a compiled program: run the native code of the function.
bool zn::rt::Machine::exec(const Func* f, Slot* base) {
  int st = f->native(*this, base);
  if (st == 1) { error = "panic: Uncaught " + exceptionText(thrown); thrown = nullptr; return false; }
  return st == 0;
}

int main() {
  return zn::rt::runProgramPacked(reinterpret_cast<const unsigned char*>(kModule), kModuleSize, kNatives, 2);
}
