// docs/reports/compat.md from a results file (tests/compat/results/<date>.json) and the hand-written tests/compat/notes.md.
const NAMES = { 'zinc-sim': 'Zinc sim', 'zinc-sim-strict': 'Zinc sim strict', 'zinc-native': 'Zinc native', 'zinc-native-strict': 'Zinc native strict', node: 'Node', deno: 'Deno', bun: 'Bun', qjs: 'QuickJS' };
const SYM = { pass: '✓', fail: '✗', rejected: 'R', unsupported: 'U', timeout: 'T' };
const pct = (a, b) => b ? `${(100 * a / b).toFixed(b >= 1000 ? 1 : 0)}%` : '—';
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const norm = (s) => String(s ?? '').replace(/'[^']*'/g, "'…'").replace(/"[^"]*"/g, '"…"').replace(/«[^»]*»/g, '«…»').replace(/\b\d+\b/g, 'N').slice(0, 110);

function tally(list, eng) {
  const t = { pass: 0, total: 0, sub: 0, subTotal: 0 };
  for (const x of list) {
    const r = x.r?.[eng];
    if (!r) continue;
    t.total++;
    t[r[0]] = (t[r[0]] ?? 0) + 1;
    if (r.length >= 5 && typeof r[3] === 'number') { t.sub += r[3]; t.subTotal += r[4]; }
  }
  return t;
}
const cell = (t) => t.total ? `${t.pass}/${t.total} (${pct(t.pass, t.total)})` : '—';
const breakdown = (t) => ['fail', 'rejected', 'unsupported', 'timeout'].filter(k => t[k]).map(k => `${SYM[k]} ${t[k]}`).join(', ');

export function report(res, M, notes) {
  const engines = Object.keys(res.engines);
  const zinc = engines.filter(e => e.startsWith('zinc'));
  const refs = engines.filter(e => !e.startsWith('zinc'));
  const all = Object.entries(res.tests).map(([id, t]) => ({ id, ...t }));
  const run = all.filter(t => !t.skip);
  const suite = (s) => run.filter(t => t.suite === s);
  const L = [];
  const row = (cells) => L.push(`| ${cells.join(' | ')} |`);
  const head = (cells) => { row(cells); row(cells.map(() => '---')); };

  L.push('# Standards conformance', '',
    `Generated by \`zinc compat\` (tests/compat/run.mjs) on ${res.date} from Zinc \`${res.commit}\`${res.dirty ? ' (with uncommitted compiler / runtime changes)' : ''}, ${res.platform}, in ${res.durationS} s. Do not edit: rerun \`zinc compat\`. The raw per-test results are in [tests/compat/results/${res.date}.json](../../tests/compat/results/${res.date}.json).`, '',
    'Zinc runs every test four ways: the **sim** oracle (JavaScript on Node) and the **native** host build, each in the **gradual** profile (`any` is `Dyn`) and the **strict** one (`any` refused). Node, Deno, Bun and QuickJS run the same tests as reference engines, with the real harnesses (test262 `assert.js`, WPT `testharness.js`). Status letters: ✓ pass, ✗ fail (wrong result or crash), **R** rejected at compile time (a `Z` or TypeScript diagnostic: the program is outside Zinc\'s subset or uses a missing API), **U** unsupported by the harness for Zinc (reflection helpers, the asynchronous testharness API, sloppy mode), **T** timeout. Rates are passes over every selected test, so R and U count as losses.', '',
    `Engines: ${engines.map(e => `${NAMES[e]}${res.engines[e] ? ` (${res.engines[e]})` : ''}`).join(', ')}. Suites: ${Object.entries(res.pins).map(([k, p]) => `[${k}](${p.repo}) \`${p.commit.slice(0, 10)}\` (${p.license})`).join(', ')}, plus ${suite('node').length} curated Node API tests (tests/compat/node).`, '');

  // ---- summary
  L.push('## Summary', '');
  head(['Suite', 'Tests', ...engines.map(e => NAMES[e])]);
  const wptSub = (e) => { const t = tally(suite('wpt'), e); return t.subTotal ? `${t.sub}/${t.subTotal} (${pct(t.sub, t.subTotal)})` : '—'; };
  const apis = M.wintertc.apis;
  const present = (e) => e.startsWith('zinc') ? apis.filter(a => zincExposure(res, a).startsWith('global')).length : apis.filter(a => res.probes[e]?.[a.probe ?? a.api]).length;
  row(['WinterTC APIs exposed as globals', apis.length, ...engines.map(e => `${present(e)}/${apis.length}`)]);
  row(['WinterTC WPT files', suite('wpt').length, ...engines.map(e => cell(tally(suite('wpt'), e)))]);
  row(['WinterTC WPT subtests', '', ...engines.map(wptSub)]);
  for (const [s, label] of [['test262', 'ECMAScript (test262)'], ['node', 'Node API (curated)'], ['quickjs', "QuickJS's own tests"]])
    row([label, suite(s).length, ...engines.map(e => cell(tally(suite(s), e)))]);
  L.push('', `${all.length - run.length} selected test262 tests use features outside Zinc's design (skipped on every engine, [below](#skipped-test262-features)).`, '');

  // ---- WinterTC
  L.push('## 1. WinterTC Minimum Common Web API', '',
    `The primary axis: the ${apis.length} interfaces and globals of Ecma TC55's [Minimum Common Web API](https://min-common-api.proposal.wintertc.org/) (2025 snapshot, ECMA-429), each with the WPT files that test it. **Exposed** is how the API reaches a Zinc program (a global declared in lib/zinc.d.ts, an import from a \`zinc:\` module, or nothing); the reference columns say whether \`globalThis\` has it (✓ / ✗) and the share of WPT subtests passed. Zinc cells count WPT files passed per profile (gradual · strict).`, '');
  head(['API', 'Spec', 'Zinc exposed', 'WPT files', 'Zinc sim', 'Zinc native', ...refs.map(e => NAMES[e])]);
  for (const a of apis) {
    const files = suite('wpt').filter(t => t.area === a.api);
    const z = (g, s) => files.length ? `${tally(files, g).pass}/${files.length} · ${tally(files, s).pass}/${files.length}` : '—';
    const refCell = (e) => {
      const has = res.probes[e]?.[a.probe ?? a.api];
      const t = tally(files, e);
      return `${has ? '✓' : '✗'}${files.length ? ` ${t.subTotal ? pct(t.sub, t.subTotal) : pct(t.pass, t.total)}` : ''}`;
    };
    row([`\`${a.api}\``, a.spec, zincExposure(res, a), files.length || '—', z('zinc-sim', 'zinc-sim-strict'), z('zinc-native', 'zinc-native-strict'), ...refs.map(refCell)]);
  }
  L.push('');
  const zr = {};
  for (const t of suite('wpt')) { const r = t.r['zinc-sim']; if (r && r[0] !== 'pass') { const k = `${SYM[r[0]]} ${norm(r[1])}`; zr[k] = (zr[k] ?? 0) + 1; } }
  L.push('Why the WPT files do not pass on Zinc (sim, gradual):', '');
  head(['Files', 'Reason']);
  for (const [k, v] of Object.entries(zr).sort((a, b) => b[1] - a[1]).slice(0, 15)) row([v, esc(k)]);
  L.push('');

  // ---- test262
  const t262 = suite('test262');
  L.push('## 2. ECMAScript (test262)', '',
    `A deterministic sample of ${t262.length} tests (every n-th file, tests/compat/manifest.json) from the built-ins Zinc implements and from the language directories. Zinc inputs get the mechanical rewrites \`zinc check --fix\` would make (\`var\` → \`let\`) and the harness passes error constructors by name; test262's \`propertyHelper.js\` and friends need property descriptors and are **U** on Zinc.`, '');
  head(['Area', 'Tests', ...engines.map(e => NAMES[e])]);
  const areas = [...new Set(t262.map(t => t.area))].sort();
  for (const a of areas) { const l = t262.filter(t => t.area === a); row([a, l.length, ...engines.map(e => cell(tally(l, e)))]); }
  row(['**all**', t262.length, ...engines.map(e => `**${cell(tally(t262, e))}**`)]);
  L.push('', 'Zinc outcomes:', '');
  head(['Engine', 'Pass', 'Fail', 'Rejected', 'Unsupported', 'Timeout']);
  for (const e of zinc) { const t = tally(t262, e); row([NAMES[e], t.pass, t.fail ?? 0, t.rejected ?? 0, t.unsupported ?? 0, t.timeout ?? 0]); }
  L.push('');
  const lang = t262.filter(t => t.area.startsWith('language/') && t.sub);
  if (lang.length) {
    L.push('<details><summary>Language, by directory</summary>', '');
    head(['Directory', 'Tests', ...engines.map(e => NAMES[e])]);
    for (const d of [...new Set(lang.map(t => `${t.area}/${t.sub}`))].sort()) {
      const l = lang.filter(t => `${t.area}/${t.sub}` === d);
      row([d.replace('language/', ''), l.length, ...engines.map(e => `${tally(l, e).pass}/${l.length}`)]);
    }
    L.push('', '</details>', '');
  }
  const skips = {};
  for (const t of all.filter(t => t.skip)) for (const f of t.skip.replace(/^feature /, '').split(', ')) skips[f] = (skips[f] ?? 0) + 1;
  L.push('### Skipped test262 features', '', 'Outside Zinc by design (docs/guide/02-language.md: no reflection, no regex engine, no symbols beyond `Symbol.iterator` / `Symbol.dispose`, no typed arrays yet) or host-specific; skipped on every engine so the rates compare the same tests. Tests carrying several features count once per feature.', '');
  L.push(Object.entries(skips).sort((a, b) => b[1] - a[1]).map(([f, n]) => `\`${f}\` ${n}`).join(' · '), '');

  // ---- Node API
  L.push('## 3. Node API (curated)', '', 'Self-contained tests after Node\'s test/parallel for the Node-like APIs (fs, path, os, process, buffer, timers, events, util, crypto), with a trimmed `common` (mustCall). Zinc has its own modules (`zinc:fs`, `zinc:sys`, `zinc:events`...) but no `node:*` specifiers, so these measure source compatibility with Node programs.', '');
  head(['Test', ...engines.map(e => NAMES[e])]);
  for (const t of suite('node')) row([t.id.replace('node/', ''), ...engines.map(e => SYM[t.r[e]?.[0]] ?? '—')]);
  L.push('');

  // ---- QuickJS
  L.push("## 4. QuickJS's own tests", '', "quickjs-ng's tests/, one test per `test_*()` call (the function plus the declarations it reaches; `qjs:os` / `qjs:std` imports removed). The `qjs` binary here is Bellard's QuickJS, so its misses on quickjs-ng-only features are expected.", '');
  head(['File', 'Tests', ...engines.map(e => NAMES[e])]);
  const qfiles = [...new Set(suite('quickjs').map(t => t.area))];
  for (const f of qfiles) { const l = suite('quickjs').filter(t => t.area === f); row([f, l.length, ...engines.map(e => `${tally(l, e).pass}/${l.length}`)]); }
  L.push('');

  // ---- clusters
  L.push('## 5. Zinc failure clusters', '', 'Programs Zinc compiled but ran wrongly, grouped by the first error (all suites, all four Zinc runs). Each cluster names one test to reproduce with `zinc compat --filter <id>`.', '');
  head(['Runs', 'Engines', 'Error', 'Example']);
  const cl = {};
  for (const t of run) for (const e of zinc) {
    const r = t.r?.[e];
    if (!r || !['fail', 'timeout'].includes(r[0])) continue;
    const k = `${r[0]}: ${norm(r[1])}`;
    const c = cl[k] ??= { n: 0, eng: new Set(), ex: t.id };
    c.n++; c.eng.add(NAMES[e]);
  }
  for (const [k, c] of Object.entries(cl).sort((a, b) => b[1].n - a[1].n).slice(0, 25)) row([c.n, [...c.eng].join(', '), esc(k), `\`${c.ex}\``]);
  L.push('', 'Compile-time rejections (Zinc sim, gradual), by diagnostic:', '');
  head(['Tests', 'Diagnostic', 'Example']);
  const rj = {};
  for (const t of run) { const r = t.r?.['zinc-sim']; if (r?.[0] === 'rejected') { const k = norm(r[1]); (rj[k] ??= { n: 0, ex: t.id }).n++; } }
  for (const [k, c] of Object.entries(rj).sort((a, b) => b[1].n - a[1].n).slice(0, 25)) row([c.n, esc(k), `\`${c.ex}\``]);
  L.push('');
  const div = run.filter(t => t.r && ((t.r['zinc-sim'] && t.r['zinc-native'] && t.r['zinc-sim'][0] !== t.r['zinc-native'][0]) || (t.r['zinc-sim-strict'] && t.r['zinc-native-strict'] && t.r['zinc-sim-strict'][0] !== t.r['zinc-native-strict'][0])));
  L.push('### Sim / native divergences', '', `The sim is the oracle: a program must behave the same natively. ${div.length} test(s) differ${div.length ? ':' : '.'}`, '');
  if (div.length) {
    head(['Test', 'Sim (gradual · strict)', 'Native (gradual · strict)']);
    const s = (r) => r ? `${SYM[r[0]]}${r[0] === 'pass' ? '' : ` ${esc(norm(r[1])).slice(0, 70)}`}` : '—';
    for (const t of div.slice(0, 40)) row([`\`${t.id}\``, `${s(t.r['zinc-sim'])} · ${s(t.r['zinc-sim-strict'])}`, `${s(t.r['zinc-native'])} · ${s(t.r['zinc-native-strict'])}`]);
    L.push('');
  }
  if (notes) L.push(notes.trim(), '');
  return L.join('\n');
}

/** How a WinterTC API reaches a Zinc program, from the checkout's lib/ declarations (results.zincApis). */
function zincExposure(res, a) {
  const name = (a.probe ?? a.api).split('.')[0].replace(/\(\)$/, '');
  if (name === 'globalThis') return 'rejected (Z1015)';
  const m = res.zincApis?.[name];
  if (!m) return '—';
  if (m === 'global') return 'global';
  return `\`import\` from \`${m}\``;
}
