// Generates the fixed-point sine table shared bit-for-bit by the C++ runtime and the sim shim (RT-04).
import { writeFileSync } from 'node:fs';
const N = 4096;
const t = Array.from({ length: N }, (_, i) => Math.round(Math.sin((2 * Math.PI * i) / N) * 65536));
const K = Math.round((N / (2 * Math.PI)) * 65536);
writeFileSync(new URL('./fx_sin.h', import.meta.url), `// Generated by runtime/gen_tables.mjs. Q16.16 sine, ${N} steps per turn.\n#pragma once\nstatic const int32_t zrt_fx_sin[${N}] = {${t.join(',')}};\nstatic const int64_t zrt_fx_idx_k = ${K};\n`);
writeFileSync(new URL('../sim/fx_sin.mjs', import.meta.url), `// Generated by runtime/gen_tables.mjs.\nexport const SIN = Int32Array.from([${t.join(',')}]);\nexport const IDX_K = ${K}n;\n`);
