// Generates assets/rocket.obj (own work, CC0): a lathed low-poly rocket with four fins, coloured with the common
// `v x y z r g b` extension, no normals (zinc:3d computes smooth ones; the fins have their own vertices, so they
// stay flat). Run: node examples/3d/model/make-rocket.mjs
import fs from 'node:fs';

const v = [], f = [];
const vert = (x, y, z, c) => { v.push(`v ${x.toFixed(4)} ${y.toFixed(4)} ${z.toFixed(4)} ${c.join(' ')}`); return v.length; };
const WHITE = [0.92, 0.92, 0.95], RED = [0.85, 0.15, 0.12], GREY = [0.35, 0.35, 0.4], BLUE = [0.2, 0.45, 0.9];
// profile bottom -> top: [radius, y, colour]
// (a repeated point starts a new colour band: vertices are not shared across it, so the band edge stays crisp)
const prof = [[0.0, -1.7, GREY], [0.3, -1.7, GREY], [0.42, -1.4, GREY], [0.5, -1.1, GREY], [0.5, -1.1, WHITE], [0.52, -0.1, WHITE],
  [0.52, -0.1, BLUE], [0.52, 0.3, BLUE], [0.52, 0.3, WHITE], [0.48, 0.9, WHITE], [0.48, 0.9, RED], [0.4, 1.2, RED], [0.25, 1.5, RED], [0.0, 1.75, RED]];
const SEG = 20;
const ring = prof.map(([r, y, c]) => {
  const ids = [];
  for (let j = 0; j < SEG; j++) { const a = 2 * Math.PI * j / SEG; ids.push(vert(r * Math.sin(a), y, r * Math.cos(a), c)); }
  return ids;
});
for (let i = 0; i + 1 < ring.length; i++) {
  for (let j = 0; j < SEG; j++) {
    const a = ring[i][j], b = ring[i][(j + 1) % SEG], c = ring[i + 1][(j + 1) % SEG], d = ring[i + 1][j];
    f.push(`f ${a} ${b} ${c} ${d}`);  // counter-clockwise seen from outside
  }
}
// fins: a triangle in the (radial, y) plane, both sides, own vertices
for (let k = 0; k < 4; k++) {
  const a = Math.PI / 4 + k * Math.PI / 2, s = Math.sin(a), c = Math.cos(a);
  const pts = [[0.45, -0.6], [0.45, -1.5], [1.05, -1.75], [1.0, -1.25]];
  const side = (sign) => {
    const off = 0.03 * sign;  // half thickness, along the tangent
    const ids = pts.map(([r, y]) => vert(r * s + off * c, y, r * c - off * s, RED));
    f.push(sign > 0 ? `f ${ids.join(' ')}` : `f ${ids.reverse().join(' ')}`);
  };
  side(1); side(-1);
}
fs.writeFileSync(new URL('./assets/rocket.obj', import.meta.url), `# rocket.obj - zinc:3d example model (CC0), generated by make-rocket.mjs\n${v.join('\n')}\n${f.join('\n')}\n`);
console.log(`${v.length} vertices, ${f.length} faces`);
