// Platform capabilities (docs/targets/capabilities.md): what a profile offers, and whether a program, a plugin, a
// module or a test can run there.
//
// Capabilities = targets/capabilities.json (hardware: touch, keyboard, net, fs...) + the compiler's profile table
// (heap, numbers, fpu, screen size). Requirements are strings, all of which must hold:
//   "touch"              the capability is true, "plugin" or "optional" (a plugin or the board can provide it)
//   "touch|pointer"      any of them
//   "!eink"              the capability is false or absent
//   "heap>=256K"         numeric comparisons: heap (bytes; K / M suffixes), width, height (>= <= > < =)
//   "numbers=f64"        string equality: numbers (f64 f32 fx12), fpu (true / false)
import * as fs from 'node:fs';
import * as path from 'node:path';
import { ZINC_ROOT } from './frontend.ts';

export type Caps = Record<string, boolean | string | number>;
export interface ProfileLike { number: string; width: number; height: number; heap: number; noFpu?: boolean }

let table: Record<string, Caps> | null = null;
function hardware(): Record<string, Caps> {
  if (table === null) {
    const raw = JSON.parse(fs.readFileSync(path.join(ZINC_ROOT, 'targets/capabilities.json'), 'utf8')) as Record<string, Caps>;
    delete raw.$comment;
    table = raw;
  }
  return table;
}

/** Everything known about a profile: hardware flags plus heap / numbers / fpu / screen size. */
export function capsFor(profile: string, p: ProfileLike): Caps {
  return { ...(hardware()[profile] ?? {}), heap: p.heap, numbers: p.number, fpu: !p.noFpu, width: p.width, height: p.height };
}

function bytes(v: string): number {
  const m = /^(\d+(?:\.\d+)?)\s*([KMG]?)i?B?$/i.exec(v.trim());
  if (!m) return Number(v);
  return Number(m[1]) * ({ '': 1, K: 1024, M: 1 << 20, G: 1 << 30 } as Record<string, number>)[m[2].toUpperCase()];
}
/** gpu and tier are ladders (`requires gpu>=gles3`, `tier>=T2`); -1: not a ladder value. Same rules as next/src/frontend/capabilities.cpp. */
function ladder(name: string, v: unknown): number {
  const s = String(v);
  if (name === 'tier') return /^T[0-4]$/.test(s) ? Number(s[1]) : -1;
  if (name !== 'gpu') return -1;
  return ['none', 'false', 'undefined', ''].includes(s) ? 0 : ['gles2', 'webgl1'].includes(s) ? 1 : ['gles3', 'webgl2'].includes(s) ? 2 : ['metal', 'vulkan', 'd3d'].includes(s) ? 3 : -1;
}
function availableNamed(name: string, v: boolean | string | number | undefined): boolean { return name === 'gpu' ? ladder(name, v) > 0 : available(v); }
function available(v: boolean | string | number | undefined): boolean { return v === true || v === 'plugin' || v === 'optional' || (typeof v === 'number' && v > 0); }

/** One requirement against the capabilities. */
export function satisfied(req: string, caps: Caps): boolean {
  const r = req.trim();
  if (r.includes('|')) return r.split('|').some(x => satisfied(x, caps));
  if (r.startsWith('!')) return !availableNamed(r.slice(1), caps[r.slice(1)]);
  const m = /^(\w+)\s*(>=|<=|>|<|=)\s*(.+)$/.exec(r);
  if (!m) return availableNamed(r, caps[r]);
  const have = caps[m[1]];
  if (typeof have === 'number') {
    const want = bytes(m[3]);
    return m[2] === '>=' ? have >= want : m[2] === '<=' ? have <= want : m[2] === '>' ? have > want : m[2] === '<' ? have < want : have === want;
  }
  const h = ladder(m[1], have), w = ladder(m[1], m[3]);
  if (h >= 0 && w >= 0 && m[2] !== '=') return m[2] === '>=' ? h >= w : m[2] === '<=' ? h <= w : m[2] === '>' ? h > w : h < w;
  return String(have) === m[3];
}
/** The requirements that do not hold (empty: compatible). */
export function unmet(requires: string[], caps: Caps): string[] { return requires.filter(r => !satisfied(r, caps)); }

/** "heap>=256K (esp32 has 160K)": a readable reason for each unmet requirement. */
export function explain(requires: string[], caps: Caps, profile: string): string {
  const k = (n: number) => n >= 1 << 20 ? `${Math.round(n / (1 << 20))}M` : `${Math.round(n / 1024)}K`;
  return unmet(requires, caps).map(r => {
    const name = /^!?(\w+)/.exec(r)?.[1] ?? r;
    const have = caps[name];
    const shown = name === 'heap' && typeof have === 'number' ? k(have) : have === undefined ? 'no' : String(have);
    return `${r} (${profile} has ${name} ${shown})`;
  }).join(', ');
}

/** `@requires heap>=192K touch|pointer` in a module's leading comments. */
export function moduleRequires(text: string): string[] {
  const m = /@requires\s+([^\n*]+)/.exec(text.slice(0, 4000));
  return m ? m[1].trim().split(/\s+/) : [];
}

/** Source of the zinc:platform module: the profile's capabilities as constants (branches on them fold away). */
export function platformModule(target: string, profile: string, caps: Caps): string {
  const lines = [
    '// Generated by zinc for this build (compiler/src/capabilities.ts): the capabilities of the target profile.',
    `export const TARGET: string = ${JSON.stringify(target)};`,
    `export const PROFILE: string = ${JSON.stringify(profile)};`,
    `export const HEAP_BYTES: i32 = ${Math.min(Number(caps.heap) || 0, 0x7fffffff)};`,
    `export const NUMBERS: string = ${JSON.stringify(String(caps.numbers))};`,
    `export const SCREEN_W: i32 = ${Number(caps.width) || 0};`,
    `export const SCREEN_H: i32 = ${Number(caps.height) || 0};`,
  ];
  for (const [k, v] of Object.entries(caps)) {
    if (['heap', 'numbers', 'width', 'height'].includes(k)) continue;
    lines.push(`export const ${k.toUpperCase()}: boolean = ${available(v)};`);
  }
  return lines.join('\n') + '\n';
}
