// Generated by zinc codegen from status.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeRemarkableStatus : zrt::Object {
  virtual int32_t battery() = 0;
  virtual bool charging() = 0;
  virtual int32_t localMinutes() = 0;
};
NativeRemarkableStatus* zinc_create_RemarkableStatus();
static NativeRemarkableStatus* zn_RemarkableStatus;
