// Generated by zinc codegen from lottie.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeLottie : zrt::Object {
  virtual int32_t parse(zrt::String json) = 0;
  virtual int32_t open(zrt::String path) = 0;
  virtual double width(int32_t a) = 0;
  virtual double height(int32_t a) = 0;
  virtual double frames(int32_t a) = 0;
  virtual double fps(int32_t a) = 0;
  virtual int32_t layers(int32_t a) = 0;
  virtual void draw(int32_t a, double frame, double x, double y, double w, double h, int32_t alpha) = 0;
  virtual void free(int32_t a) = 0;
};
NativeLottie* zinc_create_Lottie();
static NativeLottie* zn_Lottie;
