// Generated by zinc codegen from gphoto2.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeGphoto2 : zrt::Object {
  virtual zrt::Promise<zrt::String> detect() = 0;
  virtual zrt::Promise<zrt::String> open(zrt::String model, zrt::String port) = 0;
  virtual zrt::Promise<zrt::String> close() = 0;
  virtual zrt::Promise<zrt::String> summary() = 0;
  virtual zrt::Promise<zrt::String> config() = 0;
  virtual zrt::Promise<zrt::String> get(zrt::String name) = 0;
  virtual zrt::Promise<zrt::String> set(zrt::String name, zrt::String value) = 0;
  virtual zrt::Promise<zrt::String> capture(zrt::String dir) = 0;
  virtual zrt::Promise<zrt::String> trigger() = 0;
  virtual zrt::Promise<zrt::String> download(zrt::String cameraPath, zrt::String dir) = 0;
  virtual zrt::Promise<zrt::String> thumbnail(zrt::String path, int32_t w, int32_t h) = 0;
  virtual void onEvent(zrt::Fn<void(zrt::String, zrt::String)> cb) = 0;
  virtual void liveView(bool on) = 0;
  virtual void setViewSize(int32_t w, int32_t h) = 0;
  virtual int32_t liveImage() = 0;
  virtual double cameraFps() = 0;
  virtual double shownFps() = 0;
  virtual double decodeMs() = 0;
  virtual int32_t liveWidth() = 0;
  virtual int32_t liveHeight() = 0;
};
NativeGphoto2* zinc_create_Gphoto2();
static NativeGphoto2* zn_Gphoto2;
