// Generated by zinc codegen from sensor.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeSensor : zrt::Object {
  virtual double temperature() = 0;
  virtual zrt::String serial() = 0;
  virtual void setLed(bool on) = 0;
};
NativeSensor* zinc_create_Sensor();
static NativeSensor* zn_Sensor;
