// Generated by zinc codegen from device.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeDevice : zrt::Object {
  virtual bool setBacklight(int32_t level) = 0;
  virtual bool hasTouch() = 0;
  virtual int32_t heapFree() = 0;
  virtual int32_t heapMinFree() = 0;
  virtual int32_t zincHeapUsed() = 0;
  virtual int32_t zincHeapSize() = 0;
  virtual int32_t frameUs() = 0;
  virtual int32_t drawCmds() = 0;
  virtual int32_t cpuMhz() = 0;
  virtual zrt::String chip() = 0;
};
NativeDevice* zinc_create_Device();
static NativeDevice* zn_Device;
