// Generated by zinc codegen from process.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeProcess : zrt::Object {
  virtual int32_t spawn(zrt::String cmd, zrt::String args, zrt::String cwd, zrt::String env) = 0;
  virtual zrt::String error() = 0;
  virtual int32_t pid(int32_t h) = 0;
  virtual bool write(int32_t h, zrt::String data) = 0;
  virtual void closeStdin(int32_t h) = 0;
  virtual void kill(int32_t h, int32_t signal) = 0;
  virtual void onEvent(zrt::Fn<void(int32_t, int32_t, zrt::String)> cb) = 0;
};
NativeProcess* zinc_create_Process();
static NativeProcess* zn_Process;
