// Generated by zinc codegen from wasm.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeWasm : zrt::Object {
  virtual int32_t compile(zrt::Array<uint8_t> bytes) = 0;
  virtual int32_t instantiate(int32_t m) = 0;
  virtual bool linkImport(int32_t inst, zrt::String module, zrt::String name, int32_t id) = 0;
  virtual bool start(int32_t inst) = 0;
  virtual double call(int32_t inst, zrt::String name, zrt::Array<double> args) = 0;
  virtual bool failed() = 0;
  virtual int32_t argCount(int32_t inst, zrt::String name) = 0;
  virtual int32_t memorySize(int32_t inst) = 0;
  virtual zrt::Array<uint8_t> memoryRead(int32_t inst, int32_t offset, int32_t n) = 0;
  virtual bool memoryWrite(int32_t inst, int32_t offset, zrt::Array<uint8_t> data) = 0;
  virtual double globalGet(int32_t inst, zrt::String name) = 0;
  virtual void free(int32_t inst) = 0;
  virtual zrt::String error() = 0;
  virtual void onImport(zrt::Fn<double(int32_t, zrt::Array<double>)> cb) = 0;
};
NativeWasm* zinc_create_Wasm();
static NativeWasm* zn_Wasm;
