// Generated by zinc codegen from video.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeVideo : zrt::Object {
  virtual int32_t create(int32_t w, int32_t h) = 0;
  virtual bool add(int32_t p, zrt::String path) = 0;
  virtual void setOrder(int32_t p, int32_t order) = 0;
  virtual void setRepeat(int32_t p, int32_t mode) = 0;
  virtual void setBackground(int32_t p, uint32_t color) = 0;
  virtual void play(int32_t p) = 0;
  virtual void stop(int32_t p) = 0;
  virtual void pause(int32_t p, bool on) = 0;
  virtual void skip(int32_t p, int32_t delta) = 0;
  virtual void jump(int32_t p, int32_t index) = 0;
  virtual int32_t image(int32_t p) = 0;
  virtual int32_t width(int32_t p) = 0;
  virtual int32_t height(int32_t p) = 0;
  virtual int32_t index(int32_t p) = 0;
  virtual int32_t count(int32_t p) = 0;
  virtual double position(int32_t p) = 0;
  virtual double duration(int32_t p) = 0;
  virtual int32_t loops(int32_t p) = 0;
  virtual bool playing(int32_t p) = 0;
  virtual bool paused(int32_t p) = 0;
  virtual zrt::String decoder(int32_t p) = 0;
  virtual int32_t frames(int32_t p) = 0;
  virtual int32_t dropped(int32_t p) = 0;
  virtual void close(int32_t p) = 0;
};
NativeVideo* zinc_create_Video();
static NativeVideo* zn_Video;
