// Generated by zinc codegen from remote.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeRemote : zrt::Object {
  virtual zrt::Promise<zrt::String> connect(zrt::String host, int32_t port, zrt::String token) = 0;
  virtual void setReconnect(int32_t s, bool on) = 0;
  virtual void close(int32_t s) = 0;
  virtual bool connected(int32_t s) = 0;
  virtual int32_t image(int32_t s) = 0;
  virtual int32_t width(int32_t s) = 0;
  virtual int32_t height(int32_t s) = 0;
  virtual zrt::String name(int32_t s) = 0;
  virtual double fps(int32_t s) = 0;
  virtual double rtt(int32_t s) = 0;
  virtual double kbps(int32_t s) = 0;
  virtual int32_t frames(int32_t s) = 0;
  virtual void pointer(int32_t s, double x, double y, bool down, int32_t button) = 0;
  virtual void wheel(int32_t s, double dy) = 0;
  virtual void buttons(int32_t s, int32_t mask) = 0;
  virtual void onEvent(zrt::Fn<void(int32_t, zrt::String)> cb) = 0;
  virtual void discover(bool on, zrt::Fn<void(zrt::String, zrt::String)> cb) = 0;
};
NativeRemote* zinc_create_Remote();
static NativeRemote* zn_Remote;
