// Generated by zinc codegen from mapping.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeMapping : zrt::Object {
  virtual bool command(zrt::String address, zrt::Array<double> numbers, zrt::Array<zrt::String> strings) = 0;
  virtual zrt::String toJson() = 0;
  virtual bool fromJson(zrt::String json) = 0;
  virtual zrt::String layerJson(int32_t layer) = 0;
  virtual zrt::String info() = 0;
  virtual int32_t layerCount() = 0;
};
NativeMapping* zinc_create_Mapping();
static NativeMapping* zn_Mapping;
