// Generated by zinc codegen from cdp.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeCdp : zrt::Object {
  virtual bool listen(int32_t port, zrt::Fn<void(int32_t, zrt::String)> onMessage) = 0;
  virtual void send(int32_t client, zrt::String msg) = 0;
  virtual double num(zrt::String msg, zrt::String key) = 0;
  virtual zrt::String str(zrt::String msg, zrt::String key) = 0;
  virtual int32_t clients() = 0;
  virtual zrt::String screenshot(int32_t maxW, int32_t maxH) = 0;
  virtual zrt::String trace(bool on) = 0;
};
NativeCdp* zinc_create_Cdp();
static NativeCdp* zn_Cdp;
