// Generated by zinc codegen from refresh.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeRmppRefresh : zrt::Object {
  virtual bool setFast(bool fast) = 0;
  virtual int32_t mode() = 0;
  virtual bool busy() = 0;
};
NativeRmppRefresh* zinc_create_RmppRefresh();
static NativeRmppRefresh* zn_RmppRefresh;
