// Generated by zinc codegen from map.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeMapEngine : zrt::Object {
  virtual zrt::String setStyle(zrt::String json) = 0;
  virtual void setSourceZoom(int32_t minZoom, int32_t maxZoom) = 0;
  virtual int32_t draw(double mx, double my, double zoom, double x, double y, double w, double h, bool fast) = 0;
  virtual zrt::String nextRequest() = 0;
  virtual void provide(zrt::String key, zrt::String data) = 0;
  virtual zrt::String stats() = 0;
};
NativeMapEngine* zinc_create_MapEngine();
static NativeMapEngine* zn_MapEngine;
