// Generated by zinc codegen from canvas2d.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeCanvas2D : zrt::Object {
  virtual void fill(zrt::Array<double> contours, uint32_t color, int32_t alpha, bool evenodd, zrt::Array<double> paint) = 0;
  virtual void image(int32_t image, double x, double y, double w, double h, int32_t alpha, bool smooth) = 0;
};
NativeCanvas2D* zinc_create_Canvas2D();
static NativeCanvas2D* zn_Canvas2D;
