// Generated by zinc codegen from svg.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeSvgEngine : zrt::Object {
  virtual int32_t parse(zrt::String text) = 0;
  virtual zrt::String error() = 0;
  virtual double width(int32_t doc) = 0;
  virtual double height(int32_t doc) = 0;
  virtual void draw(int32_t doc, double x, double y, double w, double h, int32_t alpha) = 0;
  virtual int32_t items(int32_t doc) = 0;
  virtual void dispose(int32_t doc) = 0;
};
NativeSvgEngine* zinc_create_SvgEngine();
static NativeSvgEngine* zn_SvgEngine;
