// Generated by zinc codegen from socket.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeSocket : zrt::Object {
  virtual int32_t connect(zrt::String host, int32_t port) = 0;
  virtual int32_t connectUnix(zrt::String path) = 0;
  virtual int32_t listen(zrt::String host, int32_t port) = 0;
  virtual int32_t listenUnix(zrt::String path) = 0;
  virtual int32_t udp(zrt::String host, int32_t port) = 0;
  virtual bool write(int32_t h, zrt::Array<uint8_t> data) = 0;
  virtual bool writeText(int32_t h, zrt::String data) = 0;
  virtual bool sendTo(int32_t h, zrt::String host, int32_t port, zrt::Array<uint8_t> data) = 0;
  virtual void end(int32_t h) = 0;
  virtual void close(int32_t h) = 0;
  virtual int32_t localPort(int32_t h) = 0;
  virtual zrt::String remoteAddress(int32_t h) = 0;
  virtual int32_t remotePort(int32_t h) = 0;
  virtual int32_t lookup(zrt::String host) = 0;
  virtual zrt::String error() = 0;
  virtual void onEvent(zrt::Fn<void(int32_t, int32_t, int32_t, zrt::String, zrt::Array<uint8_t>)> cb) = 0;
};
NativeSocket* zinc_create_Socket();
static NativeSocket* zn_Socket;
