// Generated by zinc codegen from ffi.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeFfi : zrt::Object {
  virtual int32_t open(zrt::String path) = 0;
  virtual void close(int32_t lib) = 0;
  virtual double sym(int32_t lib, zrt::String name) = 0;
  virtual zrt::String error() = 0;
  virtual double call(double fn, zrt::Array<double> ints, zrt::Array<zrt::String> strs, zrt::Array<int32_t> strAt, zrt::Array<double> floats, int32_t ret) = 0;
  virtual zrt::String text() = 0;
  virtual double alloc(int32_t n) = 0;
  virtual void free(double p) = 0;
  virtual zrt::Array<uint8_t> read(double p, int32_t n) = 0;
  virtual void write(double p, zrt::Array<uint8_t> data) = 0;
  virtual zrt::String readCString(double p) = 0;
};
NativeFfi* zinc_create_Ffi();
static NativeFfi* zn_Ffi;
