// Generated by zinc codegen from webview.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeWebview : zrt::Object {
  virtual int32_t create(double x, double y, double w, double h) = 0;
  virtual void setBounds(int32_t v, double x, double y, double w, double h) = 0;
  virtual void setVisible(int32_t v, bool on) = 0;
  virtual void navigate(int32_t v, zrt::String url) = 0;
  virtual void loadHtml(int32_t v, zrt::String html, zrt::String baseUrl) = 0;
  virtual void eval(int32_t v, zrt::String js) = 0;
  virtual void post(int32_t v, zrt::String data) = 0;
  virtual void reply(int32_t v, int32_t id, bool ok, zrt::String result) = 0;
  virtual void close(int32_t v) = 0;
  virtual void onEvent(zrt::Fn<void(int32_t, int32_t, int32_t, zrt::String, zrt::String)> cb) = 0;
};
NativeWebview* zinc_create_Webview();
static NativeWebview* zn_Webview;
