// Generated by zinc codegen from imu.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeImu : zrt::Object {
  virtual bool open() = 0;
  virtual bool read() = 0;
  virtual float value(int32_t i) = 0;
};
NativeImu* zinc_create_Imu();
static NativeImu* zn_Imu;
