// Generated by zinc codegen from three.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeThree : zrt::Object {
  virtual int32_t parse(zrt::Array<uint8_t> data) = 0;
  virtual zrt::String error() = 0;
  virtual void free(int32_t h) = 0;
  virtual zrt::String assetInfo(int32_t h) = 0;
  virtual int32_t bufferCount(int32_t h) = 0;
  virtual zrt::String bufferUri(int32_t h, int32_t i) = 0;
  virtual void setBuffer(int32_t h, int32_t i, zrt::Array<uint8_t> data) = 0;
  virtual int32_t imageCount(int32_t h) = 0;
  virtual zrt::String imageUri(int32_t h, int32_t i) = 0;
  virtual int32_t imageDecode(int32_t h, int32_t i) = 0;
  virtual int32_t textureSource(int32_t h, int32_t t) = 0;
  virtual int32_t sceneCount(int32_t h) = 0;
  virtual int32_t defaultScene(int32_t h) = 0;
  virtual zrt::String sceneName(int32_t h, int32_t s) = 0;
  virtual void sceneNodes(int32_t h, int32_t s, zrt::Array<int32_t> out) = 0;
  virtual int32_t nodeCount(int32_t h) = 0;
  virtual zrt::String nodeName(int32_t h, int32_t n) = 0;
  virtual int32_t nodeMesh(int32_t h, int32_t n) = 0;
  virtual void nodeChildren(int32_t h, int32_t n, zrt::Array<int32_t> out) = 0;
  virtual void nodeTransform(int32_t h, int32_t n, zrt::Array<double> out) = 0;
  virtual int32_t meshCount(int32_t h) = 0;
  virtual zrt::String meshName(int32_t h, int32_t m) = 0;
  virtual int32_t primitiveCount(int32_t h, int32_t m) = 0;
  virtual int32_t primitive(int32_t h, int32_t m, int32_t p, zrt::Array<double> pos, zrt::Array<double> nrm, zrt::Array<double> uv, zrt::Array<double> col, zrt::Array<int32_t> idx) = 0;
  virtual int32_t materialCount(int32_t h) = 0;
  virtual zrt::String materialName(int32_t h, int32_t m) = 0;
  virtual void materialColor(int32_t h, int32_t m, zrt::Array<double> out) = 0;
  virtual int32_t materialTexture(int32_t h, int32_t m) = 0;
  virtual int32_t materialFlags(int32_t h, int32_t m) = 0;
  virtual int32_t animationCount(int32_t h) = 0;
  virtual int32_t skinCount(int32_t h) = 0;
  virtual int32_t decode(zrt::Array<uint8_t> data) = 0;
  virtual bool readFile(zrt::String path, zrt::Array<uint8_t> out) = 0;
  virtual int32_t pixelRatio() = 0;
};
NativeThree* zinc_create_Three();
static NativeThree* zn_Three;
