// Generated by zinc codegen from sqlite.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeSqlite : zrt::Object {
  virtual int32_t open(zrt::String path, int32_t flags) = 0;
  virtual void close(int32_t db) = 0;
  virtual bool exec(int32_t db, zrt::String sql) = 0;
  virtual zrt::String error() = 0;
  virtual double changes(int32_t db) = 0;
  virtual double lastInsertRowid(int32_t db) = 0;
  virtual bool inTransaction(int32_t db) = 0;
  virtual int32_t prepare(int32_t db, zrt::String sql) = 0;
  virtual int32_t paramCount(int32_t st) = 0;
  virtual int32_t paramIndex(int32_t st, zrt::String name) = 0;
  virtual bool bindNull(int32_t st, int32_t i) = 0;
  virtual bool bindDouble(int32_t st, int32_t i, double v) = 0;
  virtual bool bindInt(int32_t st, int32_t i, double v) = 0;
  virtual bool bindText(int32_t st, int32_t i, zrt::String v) = 0;
  virtual bool bindBlob(int32_t st, int32_t i, zrt::Array<uint8_t> v) = 0;
  virtual void clearBindings(int32_t st) = 0;
  virtual int32_t step(int32_t st) = 0;
  virtual void reset(int32_t st) = 0;
  virtual void finalize(int32_t st) = 0;
  virtual int32_t columnCount(int32_t st) = 0;
  virtual zrt::String columnName(int32_t st, int32_t i) = 0;
  virtual int32_t columnType(int32_t st, int32_t i) = 0;
  virtual double columnDouble(int32_t st, int32_t i) = 0;
  virtual zrt::String columnText(int32_t st, int32_t i) = 0;
  virtual zrt::Array<uint8_t> columnBlob(int32_t st, int32_t i) = 0;
  virtual zrt::String version() = 0;
};
NativeSqlite* zinc_create_Sqlite();
static NativeSqlite* zn_Sqlite;
