// Generated by zinc codegen from quickjs.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeQuickJS : zrt::Object {
  virtual int32_t create(double memoryLimit, double timeLimitMs, double stackSize) = 0;
  virtual void destroy(int32_t h) = 0;
  virtual bool eval(int32_t h, zrt::String src, zrt::String file) = 0;
  virtual int32_t evalAsync(int32_t h, zrt::String src, zrt::String file) = 0;
  virtual void define(int32_t h, zrt::String name, zrt::String src) = 0;
  virtual void resolver(int32_t h, zrt::Fn<zrt::String(zrt::String)> fn) = 0;
  virtual bool load(int32_t h, zrt::String name, zrt::String src) = 0;
  virtual bool call(int32_t h, zrt::String fn, zrt::Array<zrt::Dyn> args) = 0;
  virtual int32_t callAsync(int32_t h, zrt::String fn, zrt::Array<zrt::Dyn> args) = 0;
  virtual bool callRef(int32_t h, int32_t ref, zrt::Array<zrt::Dyn> args) = 0;
  virtual int32_t refNamed(int32_t h, zrt::String name) = 0;
  virtual int32_t refValue(int32_t h, zrt::Dyn v) = 0;
  virtual void unref(int32_t h, int32_t ref) = 0;
  virtual bool set(int32_t h, zrt::String name, zrt::Dyn v) = 0;
  virtual bool get(int32_t h, zrt::String name) = 0;
  virtual zrt::Dyn result(int32_t h) = 0;
  virtual zrt::Dyn error(int32_t h) = 0;
  virtual void expose(int32_t h, zrt::String name, zrt::Fn<zrt::Dyn(zrt::Array<zrt::Dyn>)> fn) = 0;
  virtual void exposeAsync(int32_t h, zrt::String name, zrt::Fn<void(int32_t, zrt::Array<zrt::Dyn>)> start) = 0;
  virtual void settle(int32_t h, int32_t id, bool ok, zrt::Dyn value, zrt::String message) = 0;
  virtual void interrupt(int32_t h) = 0;
  virtual double memoryUsed(int32_t h) = 0;
  virtual void onEvent(zrt::Fn<void(int32_t, int32_t, int32_t, zrt::Dyn)> cb) = 0;
};
NativeQuickJS* zinc_create_QuickJS();
static NativeQuickJS* zn_QuickJS;
