// Generated by zinc codegen from render3d.spec.ts. Implement per target.
#pragma once
#include "zrt.h"
#include "mod/native.h"

struct NativeRender3D : zrt::Object {
  virtual int32_t meshCreate(zrt::Array<double> pos, zrt::Array<double> nrm, zrt::Array<double> uv, zrt::Array<uint32_t> col, zrt::Array<int32_t> idx) = 0;
  virtual void meshDestroy(int32_t mesh) = 0;
  virtual int32_t target(int32_t t, int32_t w, int32_t h) = 0;
  virtual void targetDestroy(int32_t t) = 0;
  virtual void begin(int32_t t, uint32_t clear, zrt::Array<double> view, double proj, double near, double far, bool ortho) = 0;
  virtual void ambient(uint32_t color) = 0;
  virtual void light(double dx, double dy, double dz, uint32_t color) = 0;
  virtual void draw(int32_t mesh, zrt::Array<double> model, uint32_t color, int32_t texture, int32_t flags) = 0;
  virtual int32_t end() = 0;
  virtual void present(int32_t t, double x, double y, double w, double h) = 0;
};
NativeRender3D* zinc_create_Render3D();
static NativeRender3D* zn_Render3D;
