import * as system from 'zinc:system';
import * as menu from 'zinc:system/menu';
import * as dock from 'zinc:system/dock';
dock.setBadge('3');
console.log('badge', JSON.stringify(dock.getBadge()));
dock.setProgress(0.4);
dock.bounce('critical');
dock.setMenu([menu.item('new-window', 'New Window'), menu.separator(), menu.item('quit-all', 'Quit All')]);
dock.onClick('new-window', (source: string) => console.log('new window from', source));
dock.setBadge('');
console.log('badge cleared', JSON.stringify(dock.getBadge()));
setTimeout(() => system.quit(0), 100);
