// Generated by tools/system-ops from ops.json: do not edit.
export interface MenuItem { id?: string; label?: string; role?: string; accelerator?: string; enabled?: boolean; checked?: boolean; submenu?: MenuItem[]; type?: 'separator' }

export interface OpArgs {
  'notification.notify': { id: string; title: string; subtitle?: string; body?: string; icon?: string; sound?: boolean; group?: string; actions?: {id: string; title: string}[]; reply?: {placeholder?: string}; urgency?: string };
  'notification.cancel': { id: string };
  'notification.requestPermission': {  };
  'notification.delivered': {  };
  'menu.setApp': { template: MenuItem[] };
  'menu.update': { id: string; props: object };
  'menu.popup': { template: MenuItem[]; x?: number; y?: number };
  'tray.create': { id: string; icon?: string; tooltip?: string; menu?: MenuItem[]; template?: boolean };
  'tray.update': { id: string; props: object };
  'tray.remove': { id: string };
  'dialog.open': { title?: string; filters?: {name: string; extensions: string[]}[]; multiple?: boolean; directory?: boolean };
  'dialog.save': { title?: string; defaultPath?: string; filters?: {name: string; extensions: string[]}[] };
  'dialog.message': { title?: string; message: string; buttons?: string[]; kind?: 'info' | 'warning' | 'error' };
  'window.setTitle': { title: string };
  'window.setOptions': { alwaysOnTop?: boolean; transparent?: boolean; decorations?: boolean; resizable?: boolean; minSize?: [number, number]; maxSize?: [number, number] };
  'window.state.save': {  };
  'window.state.restore': {  };
  'shortcut.register': { accelerator: string };
  'shortcut.unregister': { accelerator: string };
  'instance.lock': {  };
  'deep-link.getCurrent': {  };
  'deep-link.register': { scheme: string };
  'autostart.set': { enabled: boolean };
  'autostart.get': {  };
  'dock.setBadge': { text: string };
  'dock.bounce': { critical?: boolean };
  'power.preventSleep': { reason?: string };
  'power.release': { token: number };
  'clipboard.writeRich': { text: string; html?: string };
  'clipboard.readRich': {  };
  'opener.open': { target: string };
  'window.confirmClose': {  };
  'notification.backend': {  };
  'menu.dump': {  };
  'menu.perform': { path: string };
}

export interface OpResult {
  'notification.notify': {id: string; delivered: boolean; reason?: string};
  'notification.cancel': {};
  'notification.requestPermission': {state: 'granted' | 'denied' | 'default' | 'unsupported'};
  'notification.delivered': {items: {id: string; title: string; body: string}[]};
  'menu.setApp': {};
  'menu.update': {};
  'menu.popup': {id: string | null};
  'tray.create': {};
  'tray.update': {};
  'tray.remove': {};
  'dialog.open': {paths: string[] | null};
  'dialog.save': {path: string | null};
  'dialog.message': {button: number};
  'window.setTitle': {};
  'window.setOptions': {};
  'window.state.save': {};
  'window.state.restore': {restored: boolean};
  'shortcut.register': {ok: boolean};
  'shortcut.unregister': {};
  'instance.lock': {first: boolean};
  'deep-link.getCurrent': {urls: string[]};
  'deep-link.register': {ok: boolean};
  'autostart.set': {};
  'autostart.get': {enabled: boolean};
  'dock.setBadge': {};
  'dock.bounce': {};
  'power.preventSleep': {token: number};
  'power.release': {};
  'clipboard.writeRich': {};
  'clipboard.readRich': {text: string; html: string};
  'opener.open': {};
  'window.confirmClose': {};
  'notification.backend': {backend: 'native' | 'osascript' | 'dbus' | 'sim' | 'none'};
  'menu.dump': {text: string};
  'menu.perform': {ok: boolean};
}

export type OpName = keyof OpArgs;
export type EventName = 'menu-click' | 'tray-click' | 'notification-click' | 'notification-action' | 'notification-reply' | 'notification-close' | 'shortcut' | 'drop' | 'open-url' | 'second-instance' | 'power' | 'appearance' | 'window' | 'dialog-answer';

/** The permission id an op needs. */
export const PERMISSION_OF: { [op in OpName]: string };
